# Generated by Django 6.0.2 on 2026-02-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='category_icon_upload',
            field=models.ImageField(blank=True, null=True, upload_to='category/icons/'),
        ),
    ]
