# Generated by Django 6.0.2 on 2026-02-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_category_icon_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceadditionalfeature',
            name='estimate_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceadditionalfeature',
            name='estimate_time_unit',
            field=models.CharField(default='hour', max_length=20),
        ),
    ]
